---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggdistricts < 1.0 MB

<!-- badges: start -->
<!-- badges: end -->

The goal of ggdistricts is to ...

## Installation

You can install the development version of ggdistricts from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("EvaMaeRey/ggdistricts")
```





```{r}
library(ggdistricts)
library(ggplot2)
library(dplyr)

head(districts_116_flat)

districts_116_flat |>
mutate(id = 1:n()) |>
ggplot() +
  aes(state = STATE_NAME, 
      district = DISTRICT) +
  geom_district_116(drop_state = c("Alaska", "Hawaii")) +
  aes(fill = STATE_ABB) + 
  labs(title = "116th")->
plot_116th

districts_118_flat |>
mutate(id = 1:n()) |>
ggplot() +
  aes(state = STATE_NAME, 
      district = DISTRICT) +
  geom_district_118(drop_state = c("Alaska", "Hawaii")) +
  aes(fill = STATE_ABB) + 
  labs(title = "118th") ->
plot_118th

library(patchwork)
(plot_116th / plot_118th )+ plot_layout(guides = "collect")
```



```{r}
library(ggdistricts)
library(ggplot2)
library(dplyr)
districts_116_flat |>
ggplot() +
  aes(state = STATE_NAME, 
      district = DISTRICT) +
  geom_district_116(keep_state = "New York") + 
  labs(title = "116th") ->
plot_116th_ny

districts_118_flat |>
ggplot() +
  aes(state = STATE_NAME, 
      district = DISTRICT) +
  geom_district_118(keep_state = "New York") + 
  labs(title = "118th")->
plot_118th_ny

library(patchwork)
plot_116th_ny + plot_118th_ny


(plot_116th_ny + 
  geom_district_116(keep_state = "New York", 
                    keep_district = 22, fill = "darkred")) +
(plot_118th_ny + 
  geom_district_118(keep_state = "New York", 
                    keep_district = 22, fill = "darkred")) 
```





# lots of points...

This was a note about previous files in use

```{r cars}
library(sf)
sum(rapply(st_geometry(districts_116), nrow)) # big
sum(rapply(st_geometry(ggnc::nc), nrow)) # needlessly

```
